### ISSUE TITLE
Uses Reddit Login instead of Oauth

### ISSUE THREAD

**Issue by wmmnola** [rMHOC/mhoc-vote-counter#1]
We need to transfer the way the PRAW logins from using an account to using Oauth Client, perhaps migrate the data into the JSON already required for the GSpread to work.

**Comment by jb567** [comment]
[Reddit definitely wants some OAuth](https://github.com/reddit/reddit/wiki/API)

**Comment by wmmnola** [comment]
@jb567 
yep, its just more secure and an overall better system. I will begin work on a Reddit Oauth branch soon^tm
