### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by electric-blue-green** [rMHOC/mhoc-vote-counter#9]
Is this comptible with 2.7.x and 3.5.x?

**Comment by wmmnola** [comment]
I am pretty sure it is 3.5.x compatible. But its not like its difficult to switch between them in execution.

**Comment by electric-blue-green** [comment]
Its broken for everyone except andrew

**Comment by wmmnola** [comment]
whats the error?

**Comment by electric-blue-green** [comment]
trying to find out rn

**Comment by jb567** [comment]
This is a praw issue, see #10
